# ===============================
# CONFIGURAÇÕES DA BASE DE DADOS (POSTGRESQL)
# ===============================

# URL de conexão ao PostgreSQL. 
# NOTA IMPORTANTE: Ao contrário do MySQL, o PostgreSQL não cria a base de dados automaticamente via URL. 
# Precisas de criar a base de dados 'gestao_ativos' manualmente no pgAdmin ou psql antes de arrancar a aplicação.
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_ativos

# Credenciais de acesso ao PostgreSQL (O utilizador por defeito costuma ser 'postgres')
spring.datasource.username=postgres
spring.datasource.password=212195
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ===============================

# O 'update' diz ao Spring para ler as tuas classes @Entity (Equipamento e Chamado) 
# e criar ou atualizar as tabelas no PostgreSQL automaticamente quando executares o projeto.
spring.jpa.hibernate.ddl-auto=update

# Estas duas linhas fazem com que os comandos SQL gerados pelo Spring apareçam na consola.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true